setGeneric("baseCorrelation",
           function(KineticWavelets,...){standardGeneric("baseCorrelation")})
setGeneric("waveCorrelation",
           function(KineticWavelets,DNAPattern,...){standardGeneric("waveCorrelation")})
setGeneric("plotDetailAverage",
           function(waveCorrelation,...){standardGeneric("plotDetailAverage")})
setGeneric("plotSmoothAverage",
           function(waveCorrelation,...){standardGeneric("plotSmoothAverage")})
setGeneric("plotBaseCorrelation",
            function(baseCorrelation,...){standardGeneric("plotBaseCorrelation")})
setGeneric("plotPatternCorrelation",
            function(baseCorrelation,...){standardGeneric("plotPatternCorrelation")})
;