setGeneric("baseCorrelation",
           function(KineticWavelets,DNAPattern=NULL,minReadLength=200,maxReads=10000){standardGeneric("baseCorrelation")})
setGeneric("waveCorrelation",
           function(KineticWavelets,DNAPattern,maxReads=10,shiftWindow=64,totalTime=TRUE,filterNumber=1,shrink=1){standardGeneric("waveCorrelation")})
setGeneric("plotDetailAverage",
           function(waveCorrelation){standardGeneric("plotDetailAverage")})
setGeneric("plotSmoothAverage",
           function(waveCorrelation){standardGeneric("plotSmoothAverage")})
setGeneric("plotBaseCorrelation",
            function(baseCorrelation){standardGeneric("plotBaseCorrelation")})
setGeneric("plotPatternCorrelation",
            function(baseCorrelation){standardGeneric("plotPatternCorrelation")})
